[book]
title = "Hamlet's Mill"
authors = ["Giorgio De Santillana", "Hertha Von Dechend"]
description = "Web book of De Santillana's and Von Dechends 1969 publication."
language = "en"
multilingual = false
src = "src"

[output.html]
git-repository-url = "https://github.com/wheelofheaven/de-santillana-von-dechend-hamlets-mill"
git-repository-icon = "fa-github"

